spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.c0ibsblt2h8v.us-west-1.rds.amazonaws.com:3306/GREENWRITE
    username: GW0529
    password: GW0529!!

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true
        show-sql: true

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations:
      - file:src/main/resources/static/
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
        enabled: false